# Generated by Django 6.0 on 2026-01-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('WISC4', 'WISC-IV'), ('WAIS3', 'WAIS-III'), ('ETDAH_PAIS', 'E-TDAH-PAIS'), ('ETDAH_AD', 'E-TDAH-AD')], max_length=30)),
                ('test_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_progress', 'Em andamento'), ('scored', 'Corrigido'), ('locked', 'Bloqueado')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient')),
            ],
        ),
    ]
