# Generated by Django 6.0 on 2026-01-06 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wisc4NormTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('min_months', models.PositiveIntegerField()),
                ('max_months', models.PositiveIntegerField()),
                ('file_path', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wisc4Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_months', models.PositiveIntegerField()),
                ('norm_table_key', models.CharField(max_length=50)),
                ('icv', models.IntegerField()),
                ('iop', models.IntegerField()),
                ('imo', models.IntegerField()),
                ('ivp', models.IntegerField()),
                ('qit', models.IntegerField()),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wisc4_result', to='assessments.assessmentsession')),
            ],
        ),
        migrations.CreateModel(
            name='Wisc4RawScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtest', models.CharField(choices=[('SEMELHANCAS', 'Semelhanças'), ('VOCABULARIO', 'Vocabulário'), ('COMPREENSAO', 'Compreensão'), ('CUBOS', 'Cubos'), ('CONCEITOS', 'Conceitos Figurativos'), ('CODIGO', 'Código'), ('PROCURAR_SIMBOLOS', 'Procurar Símbolos'), ('DIGITOS', 'Dígitos'), ('SEQ_NUM_LETRAS', 'Sequência de Números e Letras')], max_length=40)),
                ('raw_score', models.IntegerField()),
                ('scaled_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wisc4_raw_scores', to='assessments.assessmentsession')),
            ],
            options={
                'unique_together': {('session', 'subtest')},
            },
        ),
    ]
